#pragma once

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaniaZeroLaunchcPlus::Properties
{
//# Laniatus Games Studio Inc. | NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Runtime.CompilerServices.CompilerGeneratedAttribute()][System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")] internal sealed partial class Settings: System.Configuration.ApplicationSettingsBase
	class Settings final : public System::Configuration::ApplicationSettingsBase
	{

	private:
		static Settings *defaultInstance;

	public:
		static Settings *getDefault();
	};
}
