#pragma once

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaniaZeroLaunchcPlus::Properties
{


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
//# Laniatus Games Studio Inc. | NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")][System.Diagnostics.DebuggerNonUserCodeAttribute()][System.Runtime.CompilerServices.CompilerGeneratedAttribute()] internal class Resources
	class Resources
	{

	private:
		static System::Resources::ResourceManager *resourceMan;

		static System::Globalization::CultureInfo *resourceCulture;

	public:
//# Laniatus Games Studio Inc. | NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")] internal Resources()
		Resources();

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
//# Laniatus Games Studio Inc. | NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] internal static System.Resources.ResourceManager ResourceManager
		static System::Resources::ResourceManager *getResourceManager();

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
//# Laniatus Games Studio Inc. | NOTE: The following .NET attribute has no direct equivalent in C++:
//ORIGINAL LINE: [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] internal static System.Globalization.CultureInfo Culture
		static System::Globalization::CultureInfo *getCulture();
		static void setCulture(System::Globalization::CultureInfo *value);
	};
}
